/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nsusbloader_Utilities_RcmSmash */

#ifndef _Included_nsusbloader_Utilities_RcmSmash
#define _Included_nsusbloader_Utilities_RcmSmash
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nsusbloader_Utilities_RcmSmash
 * Method:    smashLinux
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_nsusbloader_Utilities_RcmSmash_smashLinux
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     nsusbloader_Utilities_RcmSmash
 * Method:    smashWindows
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_nsusbloader_Utilities_RcmSmash_smashWindows
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
