steps:
  - name: build-standard-jar
    when:
      event: [tag, push, manual]
    image: maven:3-amazoncorretto-25-debian
    commands:
      - mvn -B -DskipTests clean package
      - mvn test -B
      - echo target/ns-usbloader-*jar
      - mkdir artifacts
      - cp target/ns-usbloader-*jar artifacts
    volumes:
      - /home/docker/woodpecker/files/m2:/root/.m2

  - name: build-windows-installer
    when:
      event: [tag, push, manual]
    image: wheatstalk/makensis:3
    commands:
      - cp target/NS-USBloader.exe misc/windows/NSIS/
      - misc/windows/update_version.sh
      - cd misc/windows/NSIS
      - makensis -V4 ./installer.nsi
      - echo Installer-*.exe
      - cp Installer-*.exe "../../../artifacts"
      - rm ./NS-USBloader.exe
      - rm ./Installer-*.exe
      - cd ../../../
    volumes:
      - /home/docker/woodpecker/files/assembly/openjdk-19.0.2:/assembly/jdk
      - /home/docker/woodpecker/files/assembly/Drivers_set.exe:/assembly/Drivers_set.exe

  - name: build-legacy-jar
    when:
      event: [tag, push, manual]
    image: maven:3-amazoncorretto-25-debian
    commands:
      - . ./.make_legacy
      - mvn -B -DskipTests clean package
      - echo target/ns-usbloader-*jar
      - cp target/ns-usbloader-*jar artifacts
    volumes:
      - /home/docker/woodpecker/files/m2:/root/.m2

  - name: build-legacy-windows-installer
    when:
      event: [tag, push, manual]
    image: wheatstalk/makensis:3
    commands:
      - cp target/NS-USBloader.exe misc/windows/NSIS/
      - misc/windows/update_version.sh legacy
      - cd misc/windows/NSIS
      - makensis -V4 ./installer.nsi
      - echo Installer-*.exe
      - cp Installer-*.exe "../../../artifacts"
      - cd ../../../
    volumes:
      - /home/docker/woodpecker/files/assembly/openjdk-25.0.1:/assembly/jdk
      - /home/docker/woodpecker/files/assembly/Drivers_set.exe:/assembly/Drivers_set.exe
  
  - name: build-mac+linux-aarch64-jar
    when:
      event: [tag, push, manual]
    image: maven:3-amazoncorretto-25-debian
    commands:
      - . ./.make_aarch64
      - mvn -B -DskipTests clean package
      - echo target/ns-usbloader-*jar
      - cp target/ns-usbloader-*jar artifacts
    volumes:
      - /home/docker/woodpecker/files/m2:/root/.m2

  - name: save-artifacts
    when:
      event: [tag, push]
    image: alpine:latest
    commands:
      - cd artifacts/
      - sha512sum ./* > ./sha512.txt
      - cd ..
      - export ARTIFACTS_DIR="$(date -d @$CI_PIPELINE_CREATED +'%Y-%m-%d %H:%M %Z')"
      - mkdir -p /builds/$CI_REPO_NAME
      - mv -v artifacts "/builds/$CI_REPO_NAME/$ARTIFACTS_DIR"
    volumes:
      - /home/www/builds:/builds